name: GitHub Actions to Publish Docker Image
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
        - main:
jobs:
  Build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: build and tag docker image
        run : |
          docker build -t ${{secrets.USERNAME}}/action-project1:v1 -f Dockerfile .
      - name: Push to Dockerhub
        run: docker login -u ${{secrets.USERNAME}} -p ${{secrets.ACCESS_TOKEN}} && docker push ${{secrets.USERNAME}}/action-project1:v1
